services:
  - name: saleor
    type: web
    env: python
    repo: https://github.com/dnilasor/saleor
    buildCommand: ./render-build.sh
    startCommand: gunicorn --bind :$PORT --workers 4 --worker-class uvicorn.workers.UvicornWorker saleor.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - key: DEBUG
        value: True
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
      - key: ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: saleor-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: saleor-redis
          property: connectionString


  - name: saleor-redis
    type: redis
    ipAllowList: [] # only allow connections from services in this Render account

  - name: saleor-dashboard
    type: web
    env: static
    repo: https://github.com/dnilasor/saleor-dashboard.git
    buildCommand: npm install && npm run build
    staticPublishPath: ./build/
    envVars:
      - key: API_URI
        value: https://saleor-z6iv.onrender.com/graphql/
      - key: APP_MOUNT_URI
        value: /dashboard/

  - type: web
    name: saleor-storefront
    env: node
    repo: https://github.com/dnilasor/react-storefront
    buildCommand: pnpm install && pnpm run build && pnpm run postbuild
    startCommand: pnpm start
    envVars:
      - key: NEXT_PUBLIC_API_URI
        value: https://saleor-z6iv.onrender.com/graphql/
      - key: NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
        value: image/avif,image/webp





databases:
  - name: saleor-db
    ipAllowList: [] # only allow connections from services in this Render account
